defaults:
  - joints_renderer: matplotlib
  - smpl_renderer: humor
  - defaults
  - _self_

run_dir: pretrained_models/mdm-smpl_clip_smplrifke_humanml3d
input: ??? # input file .txt
input_type: auto # timeline / text
single_frame: false # render or not summary frame with smpl
gender: male

guidance: 1
baseline: none
out_formats: ['txt','videojoints', 'videosmpl']

overlap_s: 0.5
ckpt: last
device: cuda
value_from: smpl

diffusion:
  weight: 1.0
  mcd: True